### ISSUE TITLE
Get up2date on the first common version on all possible distros

### ISSUE THREAD

**Issue by hwspeedy** [hardinfo2/hardinfo2#45]
Hi @hosiet and @topazus,

Version 2.1.11 should be a good build - it is accepted by both Debian/Ubuntu and Fedora/Redhat.

Can we please get that to be the base for all possible distros. - Debian and Fedora packages are the foundation for so many other distros, so if at all possible please upgrade to 2.1.11 in as many as possible distros - also old that had all the errors, thanx.

@hosiet - Please clear the old bug tracker from Ubuntu - they are all old bugs.

In advance thanx and thanx for all your work,

/hwspeedy

**Comment by hosiet** [comment]
If you know how distro works, you will know that getting packages into the main repo of old releases is not possible. That's why I suggested to drop support to old distro releases, especially EOL releases.

Instead, if you are talking about letting future distro release have hardinfo2 -- that is already what we have been doing.

All I can do for older releases is to ship hardinfo2 via -backports repos, which does not have as broad audience of course. If you want, you can distribute your releases via any 3rdparty channels as well. Consider flatpak/snap/appimage, you *yourself* will have full control.

For Fedora/RHEL side, other people can make better comment. I don't expect things to be different.

**Comment by hwspeedy** [comment]
Thanx for info - no I do not know how it works (missa learning). I have been an end user for 25 years and just want my programs to work, with out crashing all the time or as in this case, where the previous benchmark server was lost due to a FOSS initiative shutting down in Germany.

I know Debian and Fedora get EOL fast (That is fine - that's the premises) - but that is not the case for Ubuntu and Redhat (Most other distros).

**RHEL7 has 4 more years before EOL.**
https://www.redhat.com/en/blog/announcing-4-years-extended-life-cycle-support-els-red-hat-enterprise-linux-7

**Ubuntu LTS 14.04 has 2 more years before EOL**
https://wiki.ubuntu.com/Releases

**More and more Linux users turn to Rolling distros as programs are obsolete...**

As a project maintainer I will try to support both the newest (1. priority) and as long back as possible - newer destroy if it has no purpose - Am I wrong?

**Comment by hosiet** [comment]
The incentive behind long LTS support cycle has a mismatch with the pursuit of new software. People are stuck with old releases and lacks motion to upgrade, that's why Canonical and Red Hat extended their life cycles by 2 years and 4 years again (they are supposed to go to EOL this year, according to the original plan). Having support could bring revenue from legacy users, that's it.

Anyway. I doubt whether these legacy hardinfo2 users really exist, but that's just my guess. You can make the source code support the old OS, which is not a problem. The problem now is how to have hardinfo2 exposed to those old users, and pushing packages down the distro side would be difficult IMO.

**Comment by hwspeedy** [comment]
Thanx for educating me,

Not upgrading the programs will not push users forward - it will make them change to rolling releases...

The problem will only get bigger as Debian 12 and fedora 39 were such great releases.

Hope we can get hardinfo2 into ubuntu 18-> at least, thanx.

**Comment by hwspeedy** [comment]
@hosiet 
Please submit hardinfo2 version 2.1.11 to stable.
Reason for backporting to other maintained versions: **Major useability improvements** 
- Fixes lots of crashes
- fixes recommends packages to match used by the program for all git versions
- fixed non working modules loading and translations not working for all git versions
- updated benchmarks that works from slow to fast machines
- Lots of UI/UX fixes
- bug trackers cleared: DEB:21 bugs + U:12 bugs
- Total list of improvements: https://github.com/hardinfo2/hardinfo2/releases/tag/release-2.1.11

People are using this program but they have to manually install/build it due to missing update in currently maintained Debian/Ubuntu distros. 
Currently 11K records of benchmarking - Arch Branch + Fedora Branch stands for most.
Check the huge list of benchmarked cpu's on https://www.hardinfo2.org

@topazus 
Please update hardinfo2 to version 2.1.11 - it works with Fedora/EPEL dark mode via system change from old to newest gnome version (fc38-41+EL7-9+) (fixed in 2.1.11). 
Version 2.1.11 is a good edition to leave for older systems, if Redhat also want to use old programs to push users forward to newer distro versions.

We are all in the same boot, trying to make Linux the best operating system for users, thanx.

**Comment by topazus** [comment]
I just have already updated hardinfo2 to 2.1.11 two weeks ago for Fedora rawhide (Fedora 41), because publishing new tag release is a bit frequent at that time. I will update hardinfo2 to 2.1.11 for other Fedora 39,40 and epel 7-9 now.

**Comment by hosiet** [comment]
Debian 12 will receive hardinfo2 2.1.11 via the backports repository, pending a manual review that should be completed in 2 weeks. I cannot touch the software in the main repo though. Debian 11 is entering LTS status and unfortunately will not accept backported packages. Debian 10 is reaching EOL this month so no update could be made.

For Ubuntu, I have no resource of making backports now as I am not directly contributing to Ubuntu. If you happen to know any Ubuntu contributors, you can ask them to make backported packages.

**Comment by hwspeedy** [comment]
@hosiet 
Why not use updates for stable for Debian 12? (This is the active Debian version)

backports are unsecure apps and not available to users without adding repo and difficult way to install only the updates needed as instructed in Debian wiki.

This is 21 bugs removed from DebianStable.

**Please do review and consider DebianStable.**
- Where are source security reviews noted and collected for the many FOSS projects? - Do we have any common effort?
