### ISSUE TITLE
Intel's Clear Linux OS

### ISSUE THREAD

**Issue by K1ngfish3r** [hardinfo2/hardinfo2#78]
Requested here, https://github.com/clearlinux/distribution/issues/3181

Does there need to be any special patches for adding support?
cmake currently errors out with
```
...
-- LOCALEDIR = /usr/share/locale
-- Building HardInfo2 for architecture: linux-x86
-- Found no distro version - Using codename
CMake Error at CMakeLists.txt:101 (if):
  if given arguments:
    "MATCHES" "Alma*" "OR" "MATCHES "Rocky*" "OR" "MATCHES" "Fedora*" "OR"...
   Unknown arguments specified
-- Configuring incomplete, errors occurred!   
 ```

**Comment by hwspeedy** [comment]
Thanx for looking into building and packaging for ClearLinux!

> -- Found no distro version - Using codename

You somehow is missing the /etc/os-release file, which is normally present on ClearLinux.
It might be a distro building environment without /etc/os-release - you could put in a couple echo "NAME=ClearLinux" >/etc/os-release in the distro building script - then all should be good again. The CMakelist.txt uses NAME, VERSION_ID and VERSION_CODENAME.

PS: Just tested building hardinfo2 on ClearLinux42100, works fine.

**Comment by hwspeedy** [comment]
**Installed the following bundles to build for ClearLinux:**
tools
 - swupd bundle-add git
 - swupd bundle-add c-basic

libs
- swupd bundle-add qt5-dev
 - swupd bundle-add devpkg-json-glib
 - swupd bundle-add devpkg-libsoup
 - swupd bundle-add devpkg-gtk3

mkdir build; cd build; cmake -DCMAKE_BUILD_TYPE=Release .. (Remember Release for distro building otherwise no release)
make install -j (Pollutes your distro!!)
hardinfo2

Remember all the other packages that needs to be installed by hardinfo2 package and the service - see https://github.com/hardinfo2/hardinfo2?tab=readme-ov-file#setting-up-addition-tools

**Comment by K1ngfish3r** [comment]
added in CL 42360
