### ISSUE TITLE
GPU Open GL Drawing Benchmark

### ISSUE THREAD

**Issue by tutralex** [hardinfo2/hardinfo2#92]
Recently, this benchmark stopped working in the Arch distro, both with the kernel 6.11.4-arch1-1 and kernel 6.6.57-1-lts. I also have the Linux Mint 22 "Wilma" distro installed (kernel 6.8), and the "GPU Open GL Drawing" benchmark works in it.
GPU: AMD Radeon RX 6900 XT (Navi 21).

**Comment by tutralex** [comment]
In "GPU Open GL Drawing" the "This Machine..." report is missing.
[hardinfo2_report.zip](https://github.com/user-attachments/files/17452128/hardinfo2_report.zip)

**Comment by tutralex** [comment]
The problem is exclusively in my PC and it has been solved, please close this issue.

**Comment by hwspeedy** [comment]
@tutralex 
As you are a developer we need to make sure that we have a common understanding.
1. **Bug label is added when the bug is fully described and validated ONLY!**

2. Describe the issue better - what works, what does not - then the change can be debugged. Why do you think kernel versions has anything to do with a QT5 app? - More likely mesa changes, if the OpenGL benchmark does not run at all for your graphics card - that is not a hardinfo2 bug. Lots of 

**This is not a general Arch distro problem. - Confirmed working git latest build on arch latest.**

PS: The Russian translation of "This Machine" might have a problem. If looks fine in Russian html report -> no problem.

> The problem is exclusively in my PC and it has been solved, please close this issue.

**THIS IS TOO HASTY - okay to create the issue but do not add the bug flag!**
